import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Topics } from '@/types'
import { Control } from './Control'


export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by jaeyun',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', { next: { revalidate: 0 } });
    const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic: Topics) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control/>
      </body>
    </html>
  )
}
